In [ ]:
from tensorflow import keras
import tensorflow as tf
import numpy as np

In [ ]:
(x_train,y_train),(x_test,y_test)=keras.datasets.mnist.load_data()


11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

(60000, 28, 28) (60000,) (10000, 28, 28) (10000,)


In [ ]:
print(x_train[0].shape)

(28, 28)


In [ ]:
model=keras.Sequential([
    keras.layers.Conv2D(32,(3,3),activation="relu",padding="same",input_shape=(28,28,1)),
    keras.layers.MaxPool2D(pool_size=(3,3)),
    keras.layers.Dropout(0.25),
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(100,activation="relu"),
    keras.layers.Dense(10,activation="softmax")
])

In [ ]:
model.compile(optimizer="adam",loss='sparse_categorical_crossentropy',metrics=["accuracy"])

In [ ]:
model.fit(x_train,y_train,epochs=10,batch_size=32,validation_split=0.25)

Epoch 1/10
1407/1407 [==============================] - 7s 5ms/step - loss: 0.0441 - accuracy: 0.9866 - val_loss: 0.0224 - val_accuracy: 0.9935
Epoch 2/10
1407/1407 [==============================] - 6s 4ms/step - loss: 0.0355 - accuracy: 0.9895 - val_loss: 0.0236 - val_accuracy: 0.9933
Epoch 3/10
1407/1407 [==============================] - 6s 5ms/step - loss: 0.0343 - accuracy: 0.9896 - val_loss: 0.0375 - val_accuracy: 0.9889
Epoch 4/10
1407/1407 [==============================] - 6s 4ms/step - loss: 0.0348 - accuracy: 0.9894 - val_loss: 0.0390 - val_accuracy: 0.9907
Epoch 5/10
1407/1407 [==============================] - 7s 5ms/step - loss: 0.0357 - accuracy: 0.9894 - val_loss: 0.0445 - val_accuracy: 0.9893
Epoch 6/10
1407/1407 [==============================] - 6s 5ms/step - loss: 0.0292 - accuracy: 0.9915 - val_loss: 0.0410 - val_accuracy: 0.9901
Epoch 7/10
1407/1407 [==============================] - 7s 5ms/step - loss: 0.0321 - accuracy: 0.9909 - val_loss: 0.0566 - val_accuracy:

In [ ]:
model.save('2d_point.hf')

In [ ]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0965 - accuracy: 0.9823


[0.0965229868888855, 0.9822999835014343]

In [ ]:
y_predicted=model.predict(x_test)

313/313 [==============================] - 1s 2ms/step


In [ ]:
print(y_predicted[0].argmax())
print(y_predicted[1].argmax())
print(y_predicted[2].argmax())

7
2
1


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
print(y_test[:5])
print(np.max(y_predicted[:5]))

[7 2 1 0 4]
7


In [ ]:
y_pre = [np.argmax(i) for i in y_predicted]
print(y_pre[:100])

[7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 5, 4, 9, 6, 6, 5, 4, 0, 7, 4, 0, 1, 3, 1, 3, 4, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2, 3, 5, 1, 2, 4, 4, 6, 3, 5, 5, 6, 0, 4, 1, 9, 5, 7, 8, 9, 3, 7, 4, 6, 4, 3, 0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3, 6, 1, 3, 6, 9, 3, 1, 4, 1, 7, 6, 9]


In [ ]:
tf.math.confusion_matrix(labels=y_test,predictions=y_pre)

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 970,    1,    0,    0,    0,    0,    4,    2,    3,    0],
       [   1, 1120,    1,    4,    0,    0,    4,    3,    2,    0],
       [   1,    0, 1018,    2,    0,    0,    1,    7,    3,    0],
       [   0,    0,    1,  998,    0,    5,    0,    1,    5,    0],
       [   0,    0,    1,    0,  960,    0,    6,    2,    5,    8],
       [   1,    0,    0,   11,    0,  874,    4,    0,    1,    1],
       [   6,    2,    0,    1,    0,    4,  940,    0,    5,    0],
       [   0,    3,    8,    1,    5,    0,    0, 1006,    3,    2],
       [   2,    1,    2,    1,    1,    1,    0,    1,  962,    3],
       [   2,    2,    2,    4,    8,    5,    0,    3,    8,  975]],
      dtype=int32)>